[package]
name = "mame-dl2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.6"
colored = "2.0.4"
dirs = "5.0.1"
im = "15.1.0"
roxmltree = "0.18.1"
subprocess = "0.2.9"
toml = "0.8.2"
xmlparser = "0.13.6"
